import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} leading-relaxed text-slate-200 antialiased selection:bg-teal-300 selection:text-teal-900`}
      >
        <div className="min-h-screen container mx-auto relative">
          {}
          <div className="z-[-10] fixed inset-0 bg-gradient-to-br from-[#005f50] to-[#002d2b]"></div>{' '}
          {/* Darker gradient */}
          {children}
        </div>
      </body>
    </html>
  );
}
